### ISSUE TITLE
Hardcoding git path on Darwin makes configuration pointless

### ISSUE THREAD

**Issue by ttelford** [adamws/kicad-git#7]
The documentation mentions that it's mandatory to configure `.gitconfig` to have the section for the path to the `git` binary, as well as the `git_gui` option.

However, in https://github.com/adamws/kicad-git/blob/91b58a00ba53668e6269081e8609ce2992b721eb/source/git.py#L10-L13 it appears that it doesn't matter _what_ the configuration is, as it'll just use the hardcoded paths used by Homebrew.

While Homebrew is certainly a thing, [MacPorts](https://www.macports.org) (hosted by Apple until 2016) and [Fink](https://www.finkproject.org) also exist, are widely deployed, and actively developed. Simply hardcoding to Homebrew is not an effective option, especially as Apple provides `git` with macOS, and (much like TortoiseGitProc), there are other [Git GUIs for macOS](https://git-scm.com/downloads/guis?os=mac).

Even if I *do* set a configuration in a `.gitconfig`, as documented, _all_ `git` operations will then completely fail (including outside of KiCad - from a normal CLI)

    fatal: bad config line 6 in file /Users/ttelford/.gitconfig

Line 4-6, in this case, are:

```ini
  [paths]
      git = "/opt/local/bin/git"
      git_gui = "/opt/local/bit/git citool"
```

**Comment by adamws** [comment]
homebrew path in code you linked is for `DAFAULT_CONFIG` (config which is used when there is no `config.ini` found).
In README there is this line:
> To configure different command for starting git GUI or explicitly define git executable path, create **config.ini file in the plugin directory.**

I think you are confusing `.gitconfig` and `config.ini` - this works for linux & windows. I suppose it should work same for macos (although I never verified it).

**Comment by ttelford** [comment]
> I think you are confusing .gitconfig and config.ini - this works for linux & windows. I suppose it should work same for macos (although I never verified it).

I did confuse `.gitconfig` and `config.ini`. Sorry for the noise, and thank you!

I wish I could say that it _works_, but that's a slightly different issue: at least for the present, I'm seeing something to do with a conflict between the way `wish` is linked between the OS's default instance of `git` and `tk` -- and that of the Macports which I use. (ie. "_Not your problem_").
