### ISSUE TITLE
Git plugin icon does nothing when clicked.

### ISSUE THREAD

**Issue by AndKe** [adamws/kicad-git#8]
I click the icon in PCB editor - and nothing happens.
how to troubleshoot?
Linux, current KiCad  release, fresh installed plugin.

oh - and the terminal says; 
$ kicad
git: 'gui' is not a git command. See 'git --help'.

The most similar commands are
	gc
	grep
	init
	pull
	push

:)

**Comment by adamws** [comment]
Looks like git gui not installed, https://git-scm.com/docs/git-gui
As far as I know, on most distributions this is already bundled with `git` package but it might require separate installation on some.

**Comment by AndKe** [comment]
good point, I did not knew that. installed git-gui package, problem solved.
Thank you
